import { Header } from '@/widgets/header'
import { Metadata } from 'next'
import type { AppProps } from 'next/app'
import { Nunito } from 'next/font/google'
import './globals.css'

const nunito = Nunito({
	subsets: ['cyrillic'],
	variable: '--font-nunito',
	weight: ['400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
	title: 'Next Pizza',
	description: 'Generated by create next app',
}

export function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<Header />
			<main className={`${nunito.variable} antialiased`}>
				<Component {...pageProps} />
			</main>
		</>
	)
}
