import { cn } from '@/shared/lib/utils'
import { ArrowRight, ShoppingCart, User } from 'lucide-react'
import { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import Image from 'next/image'
import { Container } from '../../../shared/ui/container'
import { Button } from '../../../shared/ui/kit/button'

const nunito = Nunito({
	subsets: ['cyrillic'],
	variable: '--font-nunito',
	weight: ['400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
	title: 'Next Pizza',
	description: 'Generated by create next app',
}

export function Header({ className }: { className?: string }) {
	return (
		<header
			className={cn(
				`${nunito.variable} antialiased`,
				'border border-b ',
				className
			)}
		>
			<Container className='flex items-center justify-between py-8 '>
				<div className='flex items-center gap-4'>
					<Image src='/logo.png' width={35} height={35} alt='logo' />
					<div>
						<h1 className='text-2xl uppercase font-black'>Next Pizza</h1>
						<p className='text-sm text-gray-400 leading-3'>
							вкусней уже некуда
						</p>
					</div>
				</div>

				<div className='flex items-center gap-3'>
					<Button variant={'outline'} className='flex items-center gap-1'>
						<User size={16} />
						Войти
					</Button>
					<div>
						<Button className='group relative'>
							<b>520 ₽</b>
							<span className='h-full w-[1px] bg-white/30 mx-3' />
							<div className='flex items-center gap-1 transition duration-300 group-hover:opacity-0'>
								<ShoppingCart className='h-4 w-4 relative' strokeWidth={2} />
								<b>3</b>
							</div>
							<ArrowRight
								width={20}
								className='absolute right-5 transition duration-300 -translate-x-2 opacity-0 group-hover:opacity-100 group-hover:translate-x-0'
							/>
						</Button>
					</div>
				</div>
			</Container>
		</header>
	)
}
